on: push

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: write

env:
  COMPOSE_EXPERIMENTAL_OCI_REMOTE: "1"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          wget https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64
          mv docker-compose-linux-x86_64 compose-v2.30
          chmod +x compose-v2.30
          mv compose-v2.30 /usr/local/bin
      - run: compose-v2.30 build --push
      - run: compose-v2.30 alpha publish ghcr.io/withlogicco/postgres:${{ github.sha }}

  config:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker info
      - run: docker compose version
      - run: docker compose config --no-normalize
      - run: docker compose alpha viz --image --indentation-size=4 --networks --ports --spaces
